In [1]:
import pandas as pd

url = "https://huggingface.co/datasets/bitext/Bitext-customer-support-llm-chatbot-training-dataset/resolve/main/Bitext_Sample_Customer_Support_Training_Dataset_27K_responses-v11.csv"

df = pd.read_csv(url)

print(df.shape)
df.head()

(26872, 5)


,flags,instruction,category,intent,response
0,B,question about cancelling order {{Order Number}},ORDER,cancel_order,I've understood you have a question regarding ...
1,BQZ,i have a question about cancelling oorder {{Or...,ORDER,cancel_order,I've been informed that you have a question ab...
2,BLQZ,i need help cancelling puchase {{Order Number}},ORDER,cancel_order,I can sense that you're seeking assistance wit...
3,BL,I need to cancel purchase {{Order Number}},ORDER,cancel_order,I understood that you need assistance with can...
4,BCELN,"I cannot afford this order, cancel purchase {{...",ORDER,cancel_order,I'm sensitive to the fact that you're facing f...


In [2]:
print("\nColumn names:")
print(df.columns)


Column names:
Index(['flags', 'instruction', 'category', 'intent', 'response'], dtype='str')


In [3]:
print("\nDataset information:")
print(df.info())


Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 26872 entries, 0 to 26871
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   flags        26872 non-null  str  
 1   instruction  26872 non-null  str  
 2   category     26872 non-null  str  
 3   intent       26872 non-null  str  
 4   response     26872 non-null  str  
dtypes: str(5)
memory usage: 1.0 MB
None


In [4]:
print("\nMissing values:")
print(df.isnull().sum())


Missing values:
flags          0
instruction    0
category       0
intent         0
response       0
dtype: int64


In [5]:
print("\nIntent counts:")
print(df["intent"].value_counts())


Intent counts:
intent
check_invoice               1000
complaint                   1000
contact_customer_service    1000
edit_account                1000
switch_account              1000
check_payment_methods        999
contact_human_agent          999
delivery_period              999
get_invoice                  999
newsletter_subscription      999
payment_issue                999
registration_problems        999
cancel_order                 998
place_order                  998
track_refund                 998
change_order                 997
check_refund_policy          997
create_account               997
get_refund                   997
review                       997
set_up_shipping_address      997
delete_account               995
delivery_options             995
recover_password             995
track_order                  995
change_shipping_address      973
check_cancellation_fee       950
Name: count, dtype: int64


In [6]:
print("Categories:")
print(df["category"].unique())

print("\nNumber of categories:")
print(df["category"].nunique())

Categories:
<StringArray>
[       'ORDER',     'SHIPPING',       'CANCEL',      'INVOICE',
      'PAYMENT',       'REFUND',     'FEEDBACK',      'CONTACT',
      'ACCOUNT',     'DELIVERY', 'SUBSCRIPTION']
Length: 11, dtype: str

Number of categories:
11


In [7]:
print("Intents:")
print(df["intent"].unique())

print("\nNumber of intents:")
print(df["intent"].nunique())

Intents:
<StringArray>
[            'cancel_order',             'change_order',
  'change_shipping_address',   'check_cancellation_fee',
            'check_invoice',    'check_payment_methods',
      'check_refund_policy',                'complaint',
 'contact_customer_service',      'contact_human_agent',
           'create_account',           'delete_account',
         'delivery_options',          'delivery_period',
             'edit_account',              'get_invoice',
               'get_refund',  'newsletter_subscription',
            'payment_issue',              'place_order',
         'recover_password',    'registration_problems',
                   'review',  'set_up_shipping_address',
           'switch_account',              'track_order',
             'track_refund']
Length: 27, dtype: str

Number of intents:
27


In [8]:
pd.set_option("display.max_colwidth", 200)

df[["instruction", "category", "intent"]].sample(10, random_state=42)

,instruction,category,intent
9329,I can't talk with a human agent,CONTACT,contact_human_agent
4160,I have got to locate hte bills from {{Person Name}},INVOICE,check_invoice
18500,"I cannot pay, help me to inform of a problem with payments",PAYMENT,payment_issue
8840,I want help speaking to customer service,CONTACT,contact_customer_service
5098,I try to see th accepted payment options,PAYMENT,check_payment_methods
17250,where to sign up to the company nmewsletter,SUBSCRIPTION,newsletter_subscription
3589,I'd like to see the withdrwaal fee how can i do it,CANCEL,check_cancellation_fee
9043,I want to speak with someone,CONTACT,contact_human_agent
15800,can you help me getting bill #85632?,INVOICE,get_invoice
4384,I don't know how to take a quick look at invoice #12588,INVOICE,check_invoice


In [9]:
df[["instruction", "category", "intent"]].head(20)

,instruction,category,intent
0,question about cancelling order {{Order Number}},ORDER,cancel_order
1,i have a question about cancelling oorder {{Order Number}},ORDER,cancel_order
2,i need help cancelling puchase {{Order Number}},ORDER,cancel_order
3,I need to cancel purchase {{Order Number}},ORDER,cancel_order
4,"I cannot afford this order, cancel purchase {{Order Number}}",ORDER,cancel_order
5,can you help me cancel order {{Order Number}}?,ORDER,cancel_order
6,"I can no longer afford order {{Order Number}}, cancel it",ORDER,cancel_order
7,I am trying to cancel purchase {{Order Number}},ORDER,cancel_order
8,I have got to cancel purchase {{Order Number}},ORDER,cancel_order
9,i need help canceling purchase {{Order Number}},ORDER,cancel_order


In [10]:
df["instruction"].str.len().describe()

count    26872.000000
mean        46.889513
std         10.897578
min          6.000000
25%         40.000000
50%         48.000000
75%         55.000000
max         92.000000
Name: instruction, dtype: float64

In [11]:
import re

placeholders = set()

for text in df["instruction"]:
    found = re.findall(r"\{\{.*?\}\}", text)
    placeholders.update(found)

print("Number of unique placeholders:", len(placeholders))
print("\nPlaceholders:")
print(placeholders)


Number of unique placeholders: 9

Placeholders:
{'{{Refund Amount}}', '{{Invoice Number}}', '{{Delivery Country}}', '{{Account Category}}', '{{Currency Symbol}}', '{{Delivery City}}', '{{Order Number}}', '{{Account Type}}', '{{Person Name}}'}


In [12]:
placeholder_counts = df["instruction"].str.findall(r"\{\{.*?\}\}").explode().value_counts()

print(placeholder_counts)

instruction
{{Order Number}}        2907
{{Account Type}}        1011
{{Person Name}}          887
{{Account Category}}     822
{{Refund Amount}}        624
{{Currency Symbol}}      372
{{Delivery City}}        234
{{Delivery Country}}     177
{{Invoice Number}}         8
Name: count, dtype: int64


In [13]:
print("Duplicate instructions:", df["instruction"].duplicated().sum())

Duplicate instructions: 2237


In [14]:
print("Duplicate complete rows:", df.duplicated().sum())

Duplicate complete rows: 0


In [15]:
duplicate_instructions = df[df["instruction"].duplicated(keep=False)]

duplicate_instructions.groupby("instruction")["intent"].nunique().value_counts()

intent
1    989
Name: count, dtype: int64

## So our finding is:

#### Finding-------------------------------------->Result
- Total rows-------------------------------------->	26,872
- Duplicate instruction rows---------------------->	2,237
- Duplicate instruction groups-------------------->	989
- Duplicate groups with multiple intents---------->	0 ✅
- Complete duplicate rows------------------------->	0

2237 and 989 are different because:

- 2,237 = number of rows that belong to duplicated instructions
- 989 = number of distinct instruction texts that are duplicated

- For example:

- "I want to cancel my order"    → appears 3 times
- "I need a refund"              → appears 2 times
- "Where is my order?"            → appears 4 times

- That's 3 duplicate instruction groups, but 9 rows involved.

In [16]:
df_clean = df.drop_duplicates(subset="instruction", keep="first").copy()

print("Original shape:", df.shape)
print("Clean shape:", df_clean.shape)

print("\nIntent distribution after removing duplicates:")
print(df_clean["intent"].value_counts())

Original shape: (26872, 5)
Clean shape: (24635, 5)

Intent distribution after removing duplicates:
intent
complaint                   1000
contact_customer_service    1000
check_payment_methods        999
contact_human_agent          999
delivery_period              999
newsletter_subscription      999
payment_issue                999
registration_problems        999
place_order                  998
check_refund_policy          997
review                       997
set_up_shipping_address      997
recover_password             995
change_shipping_address      973
check_cancellation_fee       950
check_invoice                921
delete_account               918
get_refund                   918
get_invoice                  909
create_account               892
change_order                 870
switch_account               862
track_order                  807
edit_account                 777
track_refund                 707
delivery_options             660
cancel_order                 493
Nam

## We have now completed the initial data inspection:

- ✅ Dataset loaded
- ✅ Shape checked
- ✅ Missing values checked
- ✅ Categories inspected
- ✅ 27 intents identified
- ✅ Text examples inspected
- ✅ Message lengths inspected
- ✅ Placeholders inspected
- ✅ Duplicate messages checked
- ✅ Duplicate labels verified
- ✅ Duplicate instructions removed

So we're now ready to move from "understanding the data" → "preparing text for NLP."

### Next step

We'll create a separate column containing the cleaned text, while keeping the original instruction untouched

In [17]:
df_clean["cleaned_instruction"] = df_clean["instruction"].str.lower()

In [18]:
df_clean[["instruction", "cleaned_instruction"]].head(10)

,instruction,cleaned_instruction
0,question about cancelling order {{Order Number}},question about cancelling order {{order number}}
1,i have a question about cancelling oorder {{Order Number}},i have a question about cancelling oorder {{order number}}
2,i need help cancelling puchase {{Order Number}},i need help cancelling puchase {{order number}}
3,I need to cancel purchase {{Order Number}},i need to cancel purchase {{order number}}
4,"I cannot afford this order, cancel purchase {{Order Number}}","i cannot afford this order, cancel purchase {{order number}}"
5,can you help me cancel order {{Order Number}}?,can you help me cancel order {{order number}}?
6,"I can no longer afford order {{Order Number}}, cancel it","i can no longer afford order {{order number}}, cancel it"
7,I am trying to cancel purchase {{Order Number}},i am trying to cancel purchase {{order number}}
8,I have got to cancel purchase {{Order Number}},i have got to cancel purchase {{order number}}
9,i need help canceling purchase {{Order Number}},i need help canceling purchase {{order number}}


# Preprocessing

In [19]:
import re

def replace_placeholders(text):
    return re.sub(
        r"\{\{(.*?)\}\}",
        lambda match: match.group(1).replace(" ", "_").upper(),
        text
    )

df_clean["cleaned_instruction"] = df_clean["cleaned_instruction"].apply(
    replace_placeholders
)

In [20]:
df_clean[["instruction", "cleaned_instruction"]].head(10)

,instruction,cleaned_instruction
0,question about cancelling order {{Order Number}},question about cancelling order ORDER_NUMBER
1,i have a question about cancelling oorder {{Order Number}},i have a question about cancelling oorder ORDER_NUMBER
2,i need help cancelling puchase {{Order Number}},i need help cancelling puchase ORDER_NUMBER
3,I need to cancel purchase {{Order Number}},i need to cancel purchase ORDER_NUMBER
4,"I cannot afford this order, cancel purchase {{Order Number}}","i cannot afford this order, cancel purchase ORDER_NUMBER"
5,can you help me cancel order {{Order Number}}?,can you help me cancel order ORDER_NUMBER?
6,"I can no longer afford order {{Order Number}}, cancel it","i can no longer afford order ORDER_NUMBER, cancel it"
7,I am trying to cancel purchase {{Order Number}},i am trying to cancel purchase ORDER_NUMBER
8,I have got to cancel purchase {{Order Number}},i have got to cancel purchase ORDER_NUMBER
9,i need help canceling purchase {{Order Number}},i need help canceling purchase ORDER_NUMBER


### Next step: Train/Test Split

Now we need to separate our data into:

- Training data → model learns from this
- Testing data → we use this to check how well it learned

In [21]:
from sklearn.model_selection import train_test_split

X = df_clean["cleaned_instruction"]
y = df_clean["intent"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 19708
Testing samples: 4927


In [22]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (19708, 4987)
Testing TF-IDF shape: (4927, 4987)


In [24]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

model.fit(X_train_tfidf, y_train)

print("Model training completed!")

Model training completed!


In [25]:
y_pred = model.predict(X_test_tfidf)

print("Predictions generated:", len(y_pred))

Predictions generated: 4927


In [26]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

Accuracy: 0.9906636898721332
Accuracy (%): 99.06636898721331


#### But ⚠️ we should not stop at accuracy.

Because we have 27 different intents, we need to know:

Is the model performing well across all intents, or is the 99% accuracy hiding problems with particular classes?

### Next: Classification Report 📊

In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                          precision    recall  f1-score   support

            cancel_order       1.00      0.93      0.96        99
            change_order       0.94      0.98      0.96       174
 change_shipping_address       1.00      1.00      1.00       195
  check_cancellation_fee       0.99      1.00      0.99       190
           check_invoice       0.97      1.00      0.98       184
   check_payment_methods       1.00      1.00      1.00       200
     check_refund_policy       1.00      0.99      1.00       199
               complaint       1.00      1.00      1.00       200
contact_customer_service       1.00      0.98      0.99       200
     contact_human_agent       0.99      0.99      0.99       200
          create_account       0.99      0.97      0.98       178
          delete_account       0.96      1.00      0.98       184
        delivery_options       0.99      1.00      1.00       132
         delivery_period       0.99      1.00      0.99       200
         

##### We'll examine three important metrics:

- Precision → When the model predicts an intent, how often is it correct?

- Recall → Of all messages that actually belong to an intent, how many did the model find?

- F1-score → A combined measure of precision and recall.

- Support → How many test examples belong to that intent.

#### But there's something important we should investigate before claiming this model is production-ready:

🚨 We need to check the confusion matrix

* Accuracy and classification report tell us how well the model performs.

* The confusion matrix tells us which intents it confuses with which other intents.

* For example, we might discover:

- Actual: cancel_order
- Predicted: change_order

In [28]:
from sklearn.metrics import confusion_matrix
import pandas as pd

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

cm_df = pd.DataFrame(
    cm,
    index=model.classes_,
    columns=model.classes_
)

cm_df

,cancel_order,change_order,change_shipping_address,check_cancellation_fee,check_invoice,check_payment_methods,check_refund_policy,complaint,contact_customer_service,contact_human_agent,...,newsletter_subscription,payment_issue,place_order,recover_password,registration_problems,review,set_up_shipping_address,switch_account,track_order,track_refund
cancel_order,92,6,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
change_order,0,170,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
change_shipping_address,0,0,195,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_cancellation_fee,0,0,0,190,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_invoice,0,0,0,0,184,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_payment_methods,0,0,0,0,0,200,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_refund_policy,0,0,0,1,0,0,198,0,0,0,...,0,0,0,0,0,0,0,0,0,0
complaint,0,0,0,0,0,0,0,200,0,0,...,0,0,0,0,0,0,0,0,0,0
contact_customer_service,0,0,0,0,0,0,0,0,197,3,...,0,0,0,0,0,0,0,0,0,0
contact_human_agent,0,0,0,0,0,0,0,0,0,199,...,0,0,0,0,0,0,0,0,0,0


most predictions are on the diagonal, which means actual intent = predicted intent. For example, change_shipping_address has 195 correct predictions and no visible misclassifications.

- The important rows are the ones with values outside the diagonal

#### What does this tell us?

The model isn't making random mistakes.

It's mainly confusing semantically similar intents.

For example:

cancel_order
      ↕
change_order

Both involve modifying an existing order.

Similarly:

get_invoice
      ↕
check_invoice

Both involve invoices.

And:

get_refund
      ↕
track_refund

Both involve refunds.

That's actually a useful finding for your project because it shows where the language between intents overlaps.

### cancel_order row is:

92  6  0  1 ...

That means:

- 92 cancel_order → correctly predicted
- 6 → predicted as change_order
- 1 → predicted as check_cancellation_fee

Total = 99, which matches the support = 99 from your classification report.

So the confusion matrix and classification report are telling the same story from two different angles.

In [29]:
def predict_intent(message):
    # Step 1: lowercase
    cleaned_message = message.lower()
    
    # Step 2: normalize placeholders
    cleaned_message = replace_placeholders(cleaned_message)
    
    # Step 3: convert text into TF-IDF features
    message_tfidf = tfidf.transform([cleaned_message])
    
    # Step 4: predict intent
    prediction = model.predict(message_tfidf)[0]
    
    return prediction

In [30]:
message = "I want to cancel my order"

predicted_intent = predict_intent(message)

print("Customer message:", message)
print("Predicted intent:", predicted_intent)

Customer message: I want to cancel my order
Predicted intent: cancel_order


In [31]:
test_messages = [
    "Where is my order?",
    "I forgot my password",
    "What payment methods do you accept?",
    "I want to get my money back",
    "How can I change my delivery address?",
    "I want to place an order",
    "I want to cancel my purchase",
    "Can I track my refund?"
]

for message in test_messages:
    prediction = predict_intent(message)
    print(f"Message: {message}")
    print(f"Predicted intent: {prediction}")
    print("-" * 60)

Message: Where is my order?
Predicted intent: track_order
------------------------------------------------------------
Message: I forgot my password
Predicted intent: recover_password
------------------------------------------------------------
Message: What payment methods do you accept?
Predicted intent: check_payment_methods
------------------------------------------------------------
Message: I want to get my money back
Predicted intent: get_refund
------------------------------------------------------------
Message: How can I change my delivery address?
Predicted intent: change_shipping_address
------------------------------------------------------------
Message: I want to place an order
Predicted intent: place_order
------------------------------------------------------------
Message: I want to cancel my purchase
Predicted intent: cancel_order
------------------------------------------------------------
Message: Can I track my refund?
Predicted intent: track_refund
--------------

In [32]:
messy_messages = [
    # Typos
    "i wnt to cancle my order",
    "where is my oorder",
    "i forgot my pasword",

    # Informal language
    "hey where's my package?",
    "need my money back asap",
    "how do i get my order cancelled",

    # Short messages
    "refund?",
    "password help",
    "track order",

    # Different wording
    "my parcel hasn't arrived yet",
    "i dont remember my login password",
    "can i get a refund for this",

    # Noisy / casual
    "ummm... i wanna cancel this purchase",
    "pls help me find my order",
    "can u tell me what cards u accept?"
]

for message in messy_messages:
    prediction = predict_intent(message)
    print(f"Message: {message}")
    print(f"Predicted intent: {prediction}")
    print("-" * 70)

Message: i wnt to cancle my order
Predicted intent: place_order
----------------------------------------------------------------------
Message: where is my oorder
Predicted intent: recover_password
----------------------------------------------------------------------
Message: i forgot my pasword
Predicted intent: recover_password
----------------------------------------------------------------------
Message: hey where's my package?
Predicted intent: delivery_period
----------------------------------------------------------------------
Message: need my money back asap
Predicted intent: get_refund
----------------------------------------------------------------------
Message: how do i get my order cancelled
Predicted intent: get_invoice
----------------------------------------------------------------------
Message: refund?
Predicted intent: get_refund
----------------------------------------------------------------------
Message: password help
Predicted intent: recover_password
--------

In [33]:
message = "where is my oorder"

cleaned_message = message.lower()
cleaned_message = replace_placeholders(cleaned_message)

message_tfidf = tfidf.transform([cleaned_message])

probabilities = model.predict_proba(message_tfidf)[0]

results = pd.DataFrame({
    "intent": model.classes_,
    "probability": probabilities
})

results = results.sort_values(
    "probability",
    ascending=False
)

results.head(10)

,intent,probability
20,recover_password,0.123380
13,delivery_period,0.090702
16,get_refund,0.073389
2,change_shipping_address,0.055270
26,track_refund,0.050954
25,track_order,0.046708
4,check_invoice,0.043954
19,place_order,0.041607
11,delete_account,0.040165
14,edit_account,0.035978


In [34]:
import re

def normalize_typos(text):
    typo_map = {
        "oorder": "order",
        "cancle": "cancel",
        "pasword": "password",
        "puchase": "purchase"
    }

    words = text.split()

    return " ".join(
        typo_map.get(word, word)
        for word in words
    )

In [35]:
test_text = [
    "i wnt to cancle my order",
    "where is my oorder",
    "i forgot my pasword"
]

for text in test_text:
    print("Original :", text)
    print("Normalized:", normalize_typos(text))
    print()

Original : i wnt to cancle my order
Normalized: i wnt to cancel my order

Original : where is my oorder
Normalized: where is my order

Original : i forgot my pasword
Normalized: i forgot my password



In [36]:
# Apply typo normalization to training and testing data

X_train_normalized = X_train.apply(normalize_typos)
X_test_normalized = X_test.apply(normalize_typos)

X_train_normalized.head()

799          i have a question about canceling order ORDER_NUMBER
12718        i do not know how i could check the delivery methods
4036          i don't know what i need to do to check bill #37777
4158     i do not know what i need to do to check the bill #85632
7051        can uhelp me making a reclamation against ur business
Name: cleaned_instruction, dtype: str

In [37]:
# Find training examples that were actually changed

changed = X_train[X_train != X_train_normalized]

print("Number of changed training messages:", len(changed))
print("\nExamples:\n")

for original, normalized in zip(
    changed.head(10),
    X_train_normalized.loc[changed.head(10).index]
):
    print("Original  :", original)
    print("Normalized:", normalized)
    print()

Number of changed training messages: 398

Examples:

Original  : i have a question about  canceling order ORDER_NUMBER
Normalized: i have a question about canceling order ORDER_NUMBER

Original  : how do i do  a purchase
Normalized: how do i do a purchase

Original  : i have  a question about the cancellation of a ACCOUNT_TYPE account
Normalized: i have a question about the cancellation of a ACCOUNT_TYPE account

Original  : where  do i lodge a consumer claim against ur company
Normalized: where do i lodge a consumer claim against ur company

Original  : want help closing the  standard account
Normalized: want help closing the standard account

Original  : need to swap an article of  purchase ORDER_NUMBER
Normalized: need to swap an article of purchase ORDER_NUMBER

Original  : i need support modifying the  address
Normalized: i need support modifying the address

Original  : i  need to unsubscribe from the newsletter
Normalized: i need to unsubscribe from the newsletter

Original  : i

In [38]:
# Check specifically which messages contain our typo mappings

typos = ["oorder", "cancle", "pasword", "puchase", "wnt"]

for typo in typos:
    count = X_train.str.contains(
        rf"\b{typo}\b",
        regex=True
    ).sum()
    
    print(f"{typo}: {count}")

oorder: 1
cancle: 2
pasword: 0
puchase: 2
wnt: 1


### Step-1 Create the character TF-IDF vectorizer

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

char_tfidf = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=2,
    max_df=0.95
)

X_train_char = char_tfidf.fit_transform(X_train)
X_test_char = char_tfidf.transform(X_test)

print("Training Character TF-IDF shape:", X_train_char.shape)
print("Testing Character TF-IDF shape:", X_test_char.shape)

Training Character TF-IDF shape: (19708, 18013)
Testing Character TF-IDF shape: (4927, 18013)


##### Our previous model used:

Word TF-IDF
- "cancel my order"
-       ↓
- cancel | my | order | cancel my | my order

##### Now we're telling TF-IDF:

"Don't just look at whole words. Look at 3–5 character pieces inside the text."

For example:

"password"

can produce pieces such as:

- pas
- pass
- passw
- ass
- assw
- ...

So something like:

pasword

### Step 2 — Train Logistic Regression

In [40]:
from sklearn.linear_model import LogisticRegression

char_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

char_model.fit(X_train_char, y_train)

print("Character TF-IDF model training completed!")

Character TF-IDF model training completed!


In [41]:
y_pred_char = char_model.predict(X_test_char)

print("Character model predictions generated:", len(y_pred_char))

Character model predictions generated: 4927


In [42]:
from sklearn.metrics import accuracy_score

char_accuracy = accuracy_score(y_test, y_pred_char)

print("Character TF-IDF Accuracy:", char_accuracy)
print("Character TF-IDF Accuracy (%):", char_accuracy * 100)

print("\nPrevious Word TF-IDF Accuracy: 99.07%")

Character TF-IDF Accuracy: 0.9975644408362087
Character TF-IDF Accuracy (%): 99.75644408362086

Previous Word TF-IDF Accuracy: 99.07%


### For this dataset and evaluation split, Character TF-IDF + Logistic Regression achieved 99.76% accuracy compared with 99.07% for Word TF-IDF + Logistic Regression.

So next, let's test the character model on exactly those same messy messages and compare:

Word model vs Character model

In [43]:
for message in messy_messages:
    cleaned_message = message.lower()
    cleaned_message = replace_placeholders(cleaned_message)

    # Word TF-IDF prediction
    word_vector = tfidf.transform([cleaned_message])
    word_prediction = model.predict(word_vector)[0]

    # Character TF-IDF prediction
    char_vector = char_tfidf.transform([cleaned_message])
    char_prediction = char_model.predict(char_vector)[0]

    print("Message :", message)
    print("Word model :", word_prediction)
    print("Char model :", char_prediction)
    print("-" * 60)

Message : i wnt to cancle my order
Word model : place_order
Char model : cancel_order
------------------------------------------------------------
Message : where is my oorder
Word model : recover_password
Char model : track_order
------------------------------------------------------------
Message : i forgot my pasword
Word model : recover_password
Char model : recover_password
------------------------------------------------------------
Message : hey where's my package?
Word model : delivery_period
Char model : delivery_period
------------------------------------------------------------
Message : need my money back asap
Word model : get_refund
Char model : get_refund
------------------------------------------------------------
Message : how do i get my order cancelled
Word model : get_invoice
Char model : cancel_order
------------------------------------------------------------
Message : refund?
Word model : get_refund
Char model : get_refund
-----------------------------------------

In [44]:
from sklearn.metrics import confusion_matrix
import pandas as pd

cm_char = confusion_matrix(
    y_test,
    y_pred_char,
    labels=char_model.classes_
)

cm_char_df = pd.DataFrame(
    cm_char,
    index=char_model.classes_,
    columns=char_model.classes_
)

cm_char_df

,cancel_order,change_order,change_shipping_address,check_cancellation_fee,check_invoice,check_payment_methods,check_refund_policy,complaint,contact_customer_service,contact_human_agent,...,newsletter_subscription,payment_issue,place_order,recover_password,registration_problems,review,set_up_shipping_address,switch_account,track_order,track_refund
cancel_order,99,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
change_order,0,172,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
change_shipping_address,0,0,195,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_cancellation_fee,0,0,0,190,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_invoice,0,0,0,0,184,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_payment_methods,0,0,0,0,0,200,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_refund_policy,0,0,0,0,0,0,199,0,0,0,...,0,0,0,0,0,0,0,0,0,0
complaint,0,0,0,0,0,0,0,200,0,0,...,0,0,0,0,0,0,0,0,0,0
contact_customer_service,0,0,0,0,0,0,0,0,200,0,...,0,0,0,0,0,0,0,0,0,0
contact_human_agent,0,0,0,0,0,0,0,0,0,200,...,0,0,0,0,0,0,0,0,0,0


In [45]:
from sklearn.metrics import classification_report

char_report = classification_report(
    y_test,
    y_pred_char
)

print(char_report)

                          precision    recall  f1-score   support

            cancel_order       1.00      1.00      1.00        99
            change_order       0.99      0.99      0.99       174
 change_shipping_address       1.00      1.00      1.00       195
  check_cancellation_fee       1.00      1.00      1.00       190
           check_invoice       0.99      1.00      1.00       184
   check_payment_methods       1.00      1.00      1.00       200
     check_refund_policy       1.00      1.00      1.00       199
               complaint       1.00      1.00      1.00       200
contact_customer_service       1.00      1.00      1.00       200
     contact_human_agent       1.00      1.00      1.00       200
          create_account       0.99      0.99      0.99       178
          delete_account       0.99      1.00      1.00       184
        delivery_options       0.99      1.00      1.00       132
         delivery_period       0.99      1.00      1.00       200
         

In [46]:
for message in messy_messages:
    cleaned_message = message.lower()
    cleaned_message = replace_placeholders(cleaned_message)

    # Convert message to character TF-IDF
    char_vector = char_tfidf.transform([cleaned_message])

    # Get probabilities
    probabilities = char_model.predict_proba(char_vector)[0]

    # Find highest probability
    max_probability = probabilities.max()
    predicted_intent = char_model.classes_[probabilities.argmax()]

    print("Message   :", message)
    print("Prediction:", predicted_intent)
    print("Probability:", round(max_probability, 4))
    print("-" * 60)

Message   : i wnt to cancle my order
Prediction: cancel_order
Probability: 0.1672
------------------------------------------------------------
Message   : where is my oorder
Prediction: track_order
Probability: 0.0905
------------------------------------------------------------
Message   : i forgot my pasword
Prediction: recover_password
Probability: 0.6775
------------------------------------------------------------
Message   : hey where's my package?
Prediction: delivery_period
Probability: 0.2463
------------------------------------------------------------
Message   : need my money back asap
Prediction: get_refund
Probability: 0.6436
------------------------------------------------------------
Message   : how do i get my order cancelled
Prediction: cancel_order
Probability: 0.2822
------------------------------------------------------------
Message   : refund?
Prediction: get_refund
Probability: 0.4137
------------------------------------------------------------
Message   : password

In [47]:
confidence_results = []

for message in messy_messages:
    cleaned_message = message.lower()
    cleaned_message = replace_placeholders(cleaned_message)

    char_vector = char_tfidf.transform([cleaned_message])

    probabilities = char_model.predict_proba(char_vector)[0]

    predicted_intent = char_model.classes_[probabilities.argmax()]
    probability = probabilities.max()

    confidence_results.append({
        "message": message,
        "predicted_intent": predicted_intent,
        "probability": probability
    })

confidence_df = pd.DataFrame(confidence_results)

confidence_df

,message,predicted_intent,probability
0,i wnt to cancle my order,cancel_order,0.167227
1,where is my oorder,track_order,0.090465
2,i forgot my pasword,recover_password,0.677498
3,hey where's my package?,delivery_period,0.246324
4,need my money back asap,get_refund,0.643579
5,how do i get my order cancelled,cancel_order,0.282248
6,refund?,get_refund,0.413688
7,password help,recover_password,0.514754
8,track order,track_order,0.691713
9,my parcel hasn't arrived yet,delivery_period,0.528180


In [48]:
import numpy as np
import pandas as pd

# Get probabilities for every test message
test_probabilities = char_model.predict_proba(X_test_char)

# Highest probability for each prediction
max_probabilities = test_probabilities.max(axis=1)

# Whether each prediction was correct
correct_predictions = (y_pred_char == y_test.values)

confidence_test_df = pd.DataFrame({
    "true_intent": y_test.values,
    "predicted_intent": y_pred_char,
    "probability": max_probabilities,
    "correct": correct_predictions
})

confidence_test_df.head()

,true_intent,predicted_intent,probability,correct
0,contact_human_agent,contact_human_agent,0.925300,True
1,get_refund,get_refund,0.858651,True
2,check_invoice,check_invoice,0.930243,True
3,get_refund,get_refund,0.921362,True
4,delivery_period,delivery_period,0.982170,True


In [49]:
confidence_test_df["confidence_range"] = pd.cut(
    confidence_test_df["probability"],
    bins=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    labels=[
        "0-10%",
        "10-20%",
        "20-30%",
        "30-40%",
        "40-50%",
        "50-60%",
        "60-70%",
        "70-80%",
        "80-90%",
        "90-100%"
    ],
    include_lowest=True
)

confidence_summary = (
    confidence_test_df
    .groupby("confidence_range", observed=False)
    .agg(
        total=("correct", "size"),
        correct=("correct", "sum")
    )
)

confidence_summary["incorrect"] = (
    confidence_summary["total"] -
    confidence_summary["correct"]
)

confidence_summary["accuracy"] = (
    confidence_summary["correct"] /
    confidence_summary["total"]
)

confidence_summary

,total,correct,incorrect,accuracy
confidence_range,,,,
0-10%,0,0,0,NaN
10-20%,4,3,1,0.750000
20-30%,11,8,3,0.727273
30-40%,14,12,2,0.857143
40-50%,24,22,2,0.916667
50-60%,55,53,2,0.963636
60-70%,89,88,1,0.988764
70-80%,257,257,0,1.000000
80-90%,854,853,1,0.998829


In [50]:
thresholds = [0.5, 0.6, 0.7, 0.8, 0.9]

threshold_results = []

for threshold in thresholds:
    review_mask = confidence_test_df["probability"] < threshold
    
    review_count = review_mask.sum()
    auto_count = (~review_mask).sum()
    
    errors_in_auto = (
        ~confidence_test_df.loc[~review_mask, "correct"]
    ).sum()
    
    total_errors = (~confidence_test_df["correct"]).sum()
    
    threshold_results.append({
        "threshold": threshold,
        "human_review": review_count,
        "auto_classified": auto_count,
        "errors_remaining": errors_in_auto,
        "errors_caught": total_errors - errors_in_auto,
        "review_percentage": review_count / len(confidence_test_df)
    })

threshold_df = pd.DataFrame(threshold_results)

threshold_df

,threshold,human_review,auto_classified,errors_remaining,errors_caught,review_percentage
0,0.5,53,4874,4,8,0.010757
1,0.6,108,4819,2,10,0.021920
2,0.7,197,4730,1,11,0.039984
3,0.8,454,4473,1,11,0.092145
4,0.9,1308,3619,0,12,0.265476


In [51]:
CONFIDENCE_THRESHOLD = 0.70

def predict_intent_with_confidence(message):
    cleaned_message = message.lower()
    cleaned_message = replace_placeholders(cleaned_message)

    char_vector = char_tfidf.transform([cleaned_message])

    probabilities = char_model.predict_proba(char_vector)[0]

    predicted_index = probabilities.argmax()
    predicted_intent = char_model.classes_[predicted_index]
    probability = probabilities[predicted_index]

    if probability >= CONFIDENCE_THRESHOLD:
        decision = "AUTO_ROUTE"
    else:
        decision = "HUMAN_REVIEW"

    return predicted_intent, probability, decision

## we'll build the intent → support team routing mapping and integrate it into our prediction function.

In [52]:
test_message = "i wnt to cancle my order"

intent, probability, decision = predict_intent_with_confidence(test_message)

print("Message    :", test_message)
print("Intent     :", intent)
print("Probability:", round(probability, 4))
print("Decision   :", decision)

Message    : i wnt to cancle my order
Intent     : cancel_order
Probability: 0.1672
Decision   : HUMAN_REVIEW


In [53]:
intent_to_team = {
    "cancel_order": "Order Support",
    "change_order": "Order Support",
    "place_order": "Order Support",
    "track_order": "Order Support",

    "change_shipping_address": "Delivery Support",
    "set_up_shipping_address": "Delivery Support",
    "delivery_options": "Delivery Support",
    "delivery_period": "Delivery Support",

    "payment_issue": "Payment Support",
    "check_payment_methods": "Payment Support",

    "get_refund": "Refund Support",
    "track_refund": "Refund Support",
    "check_refund_policy": "Refund Support",

    "check_invoice": "Billing Support",
    "get_invoice": "Billing Support",

    "create_account": "Account Support",
    "delete_account": "Account Support",
    "edit_account": "Account Support",
    "recover_password": "Account Support",
    "registration_problems": "Account Support",
    "switch_account": "Account Support",

    "contact_customer_service": "Customer Service",
    "contact_human_agent": "Customer Service",

    "complaint": "Customer Service",
    "review": "Customer Service",

    "check_cancellation_fee": "Order Support",
    "newsletter_subscription": "Subscription Support"
}

print("Number of intents mapped:", len(intent_to_team))

Number of intents mapped: 27


### Step 1 — Create the complete ticket-routing function

In [54]:
def route_ticket(message):
    # Step 1: Predict intent + confidence
    predicted_intent, probability, decision = predict_intent_with_confidence(message)

    # Step 2: Find the support team
    support_team = intent_to_team[predicted_intent]

    # Step 3: Return the result
    return {
        "message": message,
        "predicted_intent": predicted_intent,
        "confidence": round(probability, 4),
        "decision": decision,
        "support_team": support_team
    }

In [55]:
result = route_ticket("I want to cancel my order")

result

{'message': 'I want to cancel my order',
 'predicted_intent': 'cancel_order',
 'confidence': np.float64(0.718),
 'decision': 'AUTO_ROUTE',
 'support_team': 'Order Support'}

#### So our pipeline is now becoming:

- Customer Ticket
-       ↓
- Text Preprocessing
-       ↓
- Character TF-IDF
-       ↓
- Intent Classification
-       ↓
- Confidence Check
-       ↓
- High confidence ----> AUTO_ROUTE ----> Support Team
-  │
-  ↓    
-  │
-  ↓
- Low confidence ----> HUMAN_REVIEW

In [56]:
test_tickets = [
    "I forgot my password",
    "where is my oorder",
    "can u tell me what cards u accept?",
    "I want my money back",
    "my parcel hasn't arrived yet",
    "i wnt to cancle my order",
    "I want to change my delivery address",
    "I want to delete my account",
    "Can I track my refund?",
    "I want to place an order"
]

for ticket in test_tickets:
    result = route_ticket(ticket)

    print(f"Ticket: {result['message']}")
    print(f"Intent: {result['predicted_intent']}")
    print(f"Confidence: {result['confidence']:.2%}")
    print(f"Decision: {result['decision']}")
    print(f"Team: {result['support_team']}")
    print("-" * 60)

Ticket: I forgot my password
Intent: recover_password
Confidence: 84.09%
Decision: AUTO_ROUTE
Team: Account Support
------------------------------------------------------------
Ticket: where is my oorder
Intent: track_order
Confidence: 9.05%
Decision: HUMAN_REVIEW
Team: Order Support
------------------------------------------------------------
Ticket: can u tell me what cards u accept?
Intent: check_payment_methods
Confidence: 11.87%
Decision: HUMAN_REVIEW
Team: Payment Support
------------------------------------------------------------
Ticket: I want my money back
Intent: get_refund
Confidence: 77.78%
Decision: AUTO_ROUTE
Team: Refund Support
------------------------------------------------------------
Ticket: my parcel hasn't arrived yet
Intent: delivery_period
Confidence: 52.82%
Decision: HUMAN_REVIEW
Team: Delivery Support
------------------------------------------------------------
Ticket: i wnt to cancle my order
Intent: cancel_order
Confidence: 16.72%
Decision: HUMAN_REVIEW
Tea

In [57]:
errors_df = confidence_test_df[
    confidence_test_df["correct"] == False
].sort_values("probability")

errors_df

,true_intent,predicted_intent,probability,correct,confidence_range
3070,payment_issue,delivery_period,0.171140,False,10-20%
1648,track_order,delivery_options,0.251681,False,20-30%
2449,track_order,track_refund,0.256812,False,20-30%
4691,registration_problems,create_account,0.271916,False,20-30%
845,track_order,change_order,0.320743,False,30-40%
372,create_account,delete_account,0.384189,False,30-40%
2910,get_invoice,check_invoice,0.464706,False,40-50%
1821,change_order,place_order,0.496775,False,40-50%
4575,change_order,place_order,0.539916,False,50-60%
3584,create_account,registration_problems,0.550513,False,50-60%


In [58]:
for _, row in errors_df.iterrows():
    print(f"True intent      : {row['true_intent']}")
    print(f"Predicted intent : {row['predicted_intent']}")
    print(f"Confidence       : {row['probability']:.2%}")
    print("-" * 60)

True intent      : payment_issue
Predicted intent : delivery_period
Confidence       : 17.11%
------------------------------------------------------------
True intent      : track_order
Predicted intent : delivery_options
Confidence       : 25.17%
------------------------------------------------------------
True intent      : track_order
Predicted intent : track_refund
Confidence       : 25.68%
------------------------------------------------------------
True intent      : registration_problems
Predicted intent : create_account
Confidence       : 27.19%
------------------------------------------------------------
True intent      : track_order
Predicted intent : change_order
Confidence       : 32.07%
------------------------------------------------------------
True intent      : create_account
Predicted intent : delete_account
Confidence       : 38.42%
------------------------------------------------------------
True intent      : get_invoice
Predicted intent : check_invoice
Confidence

In [59]:
error_details = pd.DataFrame({
    "message": X_test.values,
    "true_intent": y_test.values,
    "predicted_intent": y_pred_char,
    "confidence": max_probabilities,
    "correct": correct_predictions
})

error_details = error_details[
    error_details["correct"] == False
].sort_values("confidence")

error_details

,message,true_intent,predicted_intent,confidence,correct
3070,i get an error when i try to check out,payment_issue,delivery_period,0.171140,False
1648,i have to see the damn eta of my delivery helpme,track_order,delivery_options,0.251681,False
2449,order 370795561790current status,track_order,track_refund,0.256812,False
4691,i have a question about opening user profiles,registration_problems,create_account,0.271916,False
845,when will i receive ordered ORDER_NUMBER?,track_order,change_order,0.320743,False
372,i need an ACCOUNT_TYPE account,create_account,delete_account,0.384189,False
2910,semd me bill #00108,get_invoice,check_invoice,0.464706,False
1821,hep changing some products of an order,change_order,place_order,0.496775,False
4575,need help with switching some articles of an order,change_order,place_order,0.539916,False
3584,register,create_account,registration_problems,0.550513,False


In [60]:
account_examples = df_clean[
    df_clean["intent"].isin(["create_account", "registration_problems"])
][["instruction", "intent"]]

account_examples.groupby("intent").head(15)

,instruction,intent
9913,new {{Account Type}} acount for wife,create_account
9914,how to open a different fucking {{Account Type}} account for my father?,create_account
9915,new {{Account Type}} account,create_account
9916,i have a problem with creating a freemium account,create_account
9917,opdn {{Account Category}} account,create_account
9918,i need assistance creating a platinum account,create_account
9919,opening new freemium account,create_account
9920,i want help to create a {{Account Category}} account,create_account
9921,new {{Account Type}} acount,create_account
9922,I try to create a pro account for my daughter,create_account


In [61]:
for intent in ["create_account", "registration_problems"]:
    print("\n" + "=" * 70)
    print(f"INTENT: {intent}")
    print("=" * 70)

    examples = df_clean[df_clean["intent"] == intent]["instruction"].head(15)

    for i, example in enumerate(examples, 1):
        print(f"{i}. {example}")


INTENT: create_account
1. new {{Account Type}} acount for wife
2. how to open a different fucking {{Account Type}} account for my father?
3. new {{Account Type}} account
4. i have a problem with creating a freemium account
5. opdn {{Account Category}} account
6. i need assistance creating a platinum account
7. opening new freemium account
8. i want help to create  a {{Account Category}} account
9. new {{Account Type}} acount
10. I try to create a pro account for my daughter
11. how to open a premium account?
12. need assistance creating a freemium account
13. where can I get information about opening {{Account Category}} accounts?
14. I want assistance creatinga standard account
15. I don't know what to do to create a pro account

INTENT: registration_problems
1. I need support with my sign-up
2. can you help me to report errors with registrations?
3. ik do not know how i can notify of a sign-up problem
4. I want assistance to notify of an error with sign-up
5. notify of problem with 

In [62]:
order_examples = df_clean[
    df_clean["intent"].isin(["change_order", "place_order"])
][["instruction", "intent"]]

for intent in ["change_order", "place_order"]:
    print("\n" + "=" * 70)
    print(f"INTENT: {intent}")
    print("=" * 70)

    examples = df_clean[df_clean["intent"] == intent]["instruction"].head(15)

    for i, example in enumerate(examples, 1):
        print(f"{i}. {example}")


INTENT: change_order
1. I try to change several bloody items of order {{Order Number}}
2. modifying purchase {{Order Number}}
3. want help adding an item to order {{Order Number}}
4. need to change order {{Order Number}} how to do it
5. edit purchase {{Order Number}}
6. remove item from order {{Order Number}}
7. help me remove a product from purchase {{Order Number}}
8. i need assistance to add some products to order {{Order Number}}
9. how to edit order {{Order Number}}?
10. can you help me correcting purchase {{Order Number}}?
11. can I modify purchase {{Order Number}}?
12. I want to remove an item from order {{Order Number}}, I need hepl
13. want  help adding an item to purchase {{Order Number}}
14. change several articles of order {{Order Number}}
15. I want to delete an item from purchase {{Order Number}}, help me

INTENT: place_order
1. I have to order something, can I get some help?
2. how do I order a product?
3. want help to earn an few of your item
4. I am trying to order a 

In [63]:
invoice_examples = df_clean[
    df_clean["intent"].isin(["get_invoice", "check_invoice"])
][["instruction", "intent"]]

for intent in ["get_invoice", "check_invoice"]:
    print("\n" + "=" * 70)
    print(f"INTENT: {intent}")
    print("=" * 70)

    examples = df_clean[df_clean["intent"] == intent]["instruction"].head(15)

    for i, example in enumerate(examples, 1):
        print(f"{i}. {example}")


INTENT: get_invoice
1. i dont know what i need to do to download my bill #85632
2. want assistance to download invoice #85632
3. what do I need to do to get my bill from {{Person Name}}?
4. I don't know what I need to do to get the bill #12588
5. need help getting the invoices from {{Person Name}}
6. get invoice #37777
7. what do I need to do to download my bill from {{Person Name}}?
8. i lost bill #12588 could ya mail it to me
9. where do i download my goddamn invoices from {{Person Name}}
10. i dont know what i need to do to download my invoice #12588
11. I cannot find my invoice #12588, will you mail it to me?
12. I do not know what I have to do to download invoice #00108
13. want help downloading the invoice #00108
14. want asistance to download the bill #85632
15. i  do not know what i need to do to download invoice #85632

INTENT: check_invoice
1. show me invoice{{Invoice Number}}
2. need to see my invoicesfrom {{Person Name}}
3. I have to see my invoice from {{Person Name}}, he

In [64]:
from scipy.sparse import hstack

# Transform training and test data using our existing word TF-IDF
X_train_word = tfidf.transform(X_train)
X_test_word = tfidf.transform(X_test)

# Combine word + character features
X_train_combined = hstack([
    X_train_word,
    X_train_char
])

X_test_combined = hstack([
    X_test_word,
    X_test_char
])

print("Combined training shape:", X_train_combined.shape)
print("Combined test shape:", X_test_combined.shape)

Combined training shape: (19708, 23000)
Combined test shape: (4927, 23000)


In [65]:
combined_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

combined_model.fit(X_train_combined, y_train)

,"random_state random_state: int, RandomState instance, default=NoneOnly used for `solver` == 'sag', 'saga' or 'liblinear' to shuffle thedata. It has no effect on the other solvers.See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",2000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in 

In [66]:
y_pred_combined = combined_model.predict(X_test_combined)

from sklearn.metrics import accuracy_score

combined_accuracy = accuracy_score(y_test, y_pred_combined)

print("Combined Model Accuracy:", combined_accuracy)
print(f"Combined Model Accuracy: {combined_accuracy:.2%}")

Combined Model Accuracy: 0.997767404099858
Combined Model Accuracy: 99.78%


In [67]:
combined_errors = pd.DataFrame({
    "message": X_test.values,
    "true_intent": y_test.values,
    "predicted_intent": y_pred_combined,
    "correct": y_pred_combined == y_test.values
})

combined_errors = combined_errors[
    combined_errors["correct"] == False
]

print("Number of errors:", len(combined_errors))
combined_errors

Number of errors: 11


,message,true_intent,predicted_intent,correct
287,help creating account,registration_problems,create_account,False
372,i need an ACCOUNT_TYPE account,create_account,delete_account,False
400,i have a question about thepayments,payment_issue,recover_password,False
466,when can i expect a refund,get_refund,delivery_period,False
702,how can i tfack purchase ORDER_NUMBER,track_order,change_order,False
1821,hep changing some products of an order,change_order,place_order,False
2910,semd me bill #00108,get_invoice,check_invoice,False
3070,i get an error when i try to check out,payment_issue,delivery_period,False
3584,register,create_account,registration_problems,False
4575,need help with switching some articles of an order,change_order,place_order,False


In [68]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred_combined
))

                          precision    recall  f1-score   support

            cancel_order       1.00      0.99      0.99        99
            change_order       0.99      0.99      0.99       174
 change_shipping_address       1.00      1.00      1.00       195
  check_cancellation_fee       0.99      1.00      1.00       190
           check_invoice       0.99      1.00      1.00       184
   check_payment_methods       1.00      1.00      1.00       200
     check_refund_policy       1.00      1.00      1.00       199
               complaint       1.00      1.00      1.00       200
contact_customer_service       1.00      1.00      1.00       200
     contact_human_agent       1.00      1.00      1.00       200
          create_account       0.99      0.99      0.99       178
          delete_account       0.99      1.00      1.00       184
        delivery_options       1.00      1.00      1.00       132
         delivery_period       0.99      1.00      1.00       200
         

In [69]:
from sklearn.metrics import confusion_matrix

cm_combined = confusion_matrix(
    y_test,
    y_pred_combined,
    labels=combined_model.classes_
)

cm_combined_df = pd.DataFrame(
    cm_combined,
    index=combined_model.classes_,
    columns=combined_model.classes_
)

cm_combined_df

,cancel_order,change_order,change_shipping_address,check_cancellation_fee,check_invoice,check_payment_methods,check_refund_policy,complaint,contact_customer_service,contact_human_agent,...,newsletter_subscription,payment_issue,place_order,recover_password,registration_problems,review,set_up_shipping_address,switch_account,track_order,track_refund
cancel_order,98,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
change_order,0,172,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
change_shipping_address,0,0,195,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_cancellation_fee,0,0,0,190,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_invoice,0,0,0,0,184,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_payment_methods,0,0,0,0,0,200,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
check_refund_policy,0,0,0,0,0,0,199,0,0,0,...,0,0,0,0,0,0,0,0,0,0
complaint,0,0,0,0,0,0,0,200,0,0,...,0,0,0,0,0,0,0,0,0,0
contact_customer_service,0,0,0,0,0,0,0,0,200,0,...,0,0,0,0,0,0,0,0,0,0
contact_human_agent,0,0,0,0,0,0,0,0,0,200,...,0,0,0,0,0,0,0,0,0,0


In [70]:
CONFIDENCE_THRESHOLD = 0.70

def predict_intent_with_confidence_combined(message):
    # 1. Preprocess
    cleaned_message = message.lower()
    cleaned_message = replace_placeholders(cleaned_message)

    # 2. Create word + character features
    word_vector = tfidf.transform([cleaned_message])
    char_vector = char_tfidf.transform([cleaned_message])

    combined_vector = hstack([
        word_vector,
        char_vector
    ])

    # 3. Get probabilities
    probabilities = combined_model.predict_proba(combined_vector)[0]

    # 4. Find predicted intent
    predicted_index = probabilities.argmax()
    predicted_intent = combined_model.classes_[predicted_index]
    probability = probabilities[predicted_index]

    # 5. Confidence-based decision
    if probability >= CONFIDENCE_THRESHOLD:
        decision = "AUTO_ROUTE"
    else:
        decision = "HUMAN_REVIEW"

    return predicted_intent, probability, decision

In [71]:
def route_ticket(message):
    # Step 1: Predict intent + confidence using combined model
    predicted_intent, probability, decision = (
        predict_intent_with_confidence_combined(message)
    )

    # Step 2: Find the support team
    support_team = intent_to_team[predicted_intent]

    # Step 3: Return the complete result
    return {
        "message": message,
        "predicted_intent": predicted_intent,
        "confidence": probability,
        "decision": decision,
        "support_team": support_team
    }

In [72]:
result = route_ticket("I want to cancel my order")

result

{'message': 'I want to cancel my order',
 'predicted_intent': 'cancel_order',
 'confidence': np.float64(0.7465572548371578),
 'decision': 'AUTO_ROUTE',
 'support_team': 'Order Support'}

In [73]:
test_tickets = [
    "i wnt to cancle my order",
    "where is my oorder",
    "i forgot my pasword",
    "hey where's my package?",
    "need my money back asap",
    "how do i get my order cancelled",
    "refund?",
    "password help",
    "track order",
    "my parcel hasn't arrived yet",
    "i dont remember my login password",
    "can i get a refund for this",
    "ummm... i wanna cancel this purchase",
    "pls help me find my order",
    "can u tell me what cards u accept?"
]

for ticket in test_tickets:
    result = route_ticket(ticket)

    print(f"Ticket     : {result['message']}")
    print(f"Intent     : {result['predicted_intent']}")
    print(f"Confidence : {result['confidence']:.2%}")
    print(f"Decision   : {result['decision']}")
    print(f"Team       : {result['support_team']}")
    print("-" * 60)

Ticket     : i wnt to cancle my order
Intent     : cancel_order
Confidence : 16.13%
Decision   : HUMAN_REVIEW
Team       : Order Support
------------------------------------------------------------
Ticket     : where is my oorder
Intent     : track_order
Confidence : 10.76%
Decision   : HUMAN_REVIEW
Team       : Order Support
------------------------------------------------------------
Ticket     : i forgot my pasword
Intent     : recover_password
Confidence : 60.47%
Decision   : HUMAN_REVIEW
Team       : Account Support
------------------------------------------------------------
Ticket     : hey where's my package?
Intent     : delivery_period
Confidence : 26.86%
Decision   : HUMAN_REVIEW
Team       : Delivery Support
------------------------------------------------------------
Ticket     : need my money back asap
Intent     : get_refund
Confidence : 75.05%
Decision   : AUTO_ROUTE
Team       : Refund Support
------------------------------------------------------------
Ticket     : ho

In [74]:
def route_ticket(message):
    # Step 1: Predict intent + confidence
    predicted_intent, probability, decision = (
        predict_intent_with_confidence_combined(message)
    )

    # Step 2: Get the predicted support team
    predicted_team = intent_to_team[predicted_intent]

    # Step 3: Decide final routing destination
    if decision == "AUTO_ROUTE":
        routing_destination = predicted_team
    else:
        routing_destination = "Human Review Queue"

    return {
        "message": message,
        "predicted_intent": predicted_intent,
        "confidence": probability,
        "decision": decision,
        "predicted_team": predicted_team,
        "routing_destination": routing_destination
    }

In [75]:
combined_probabilities = combined_model.predict_proba(X_test_combined)

combined_max_probabilities = combined_probabilities.max(axis=1)

combined_correct_predictions = (
    y_pred_combined == y_test.values
)

combined_confidence_df = pd.DataFrame({
    "true_intent": y_test.values,
    "predicted_intent": y_pred_combined,
    "probability": combined_max_probabilities,
    "correct": combined_correct_predictions
})

In [76]:
thresholds = [0.5, 0.6, 0.7, 0.8, 0.9]

threshold_results = []

for threshold in thresholds:

    review_mask = combined_confidence_df["probability"] < threshold

    review_count = review_mask.sum()
    auto_count = (~review_mask).sum()

    errors_in_auto = (
        ~combined_confidence_df.loc[
            ~review_mask, "correct"
        ]
    ).sum()

    total_errors = (
        ~combined_confidence_df["correct"]
    ).sum()

    threshold_results.append({
        "threshold": threshold,
        "human_review": review_count,
        "auto_classified": auto_count,
        "errors_remaining": errors_in_auto,
        "errors_caught": total_errors - errors_in_auto,
        "review_percentage": review_count / len(combined_confidence_df)
    })

combined_threshold_df = pd.DataFrame(threshold_results)

combined_threshold_df

,threshold,human_review,auto_classified,errors_remaining,errors_caught,review_percentage
0,0.5,45,4882,4,7,0.009133
1,0.6,65,4862,3,8,0.013193
2,0.7,137,4790,1,10,0.027806
3,0.8,270,4657,0,11,0.054800
4,0.9,783,4144,0,11,0.158920


## Now let's make the output into a proper DataFrame.

In [77]:
results = []

for ticket in test_tickets:
    result = route_ticket(ticket)

    results.append(result)

routing_df = pd.DataFrame(results)

routing_df

,message,predicted_intent,confidence,decision,predicted_team,routing_destination
0,i wnt to cancle my order,cancel_order,0.161319,HUMAN_REVIEW,Order Support,Human Review Queue
1,where is my oorder,track_order,0.107572,HUMAN_REVIEW,Order Support,Human Review Queue
2,i forgot my pasword,recover_password,0.604712,HUMAN_REVIEW,Account Support,Human Review Queue
3,hey where's my package?,delivery_period,0.268641,HUMAN_REVIEW,Delivery Support,Human Review Queue
4,need my money back asap,get_refund,0.750476,AUTO_ROUTE,Refund Support,Refund Support
5,how do i get my order cancelled,get_invoice,0.330889,HUMAN_REVIEW,Billing Support,Human Review Queue
6,refund?,get_refund,0.444183,HUMAN_REVIEW,Refund Support,Human Review Queue
7,password help,recover_password,0.567836,HUMAN_REVIEW,Account Support,Human Review Queue
8,track order,track_order,0.787416,AUTO_ROUTE,Order Support,Order Support
9,my parcel hasn't arrived yet,delivery_period,0.382758,HUMAN_REVIEW,Delivery Support,Human Review Queue


In [78]:
routing_df["confidence"] = routing_df["confidence"].round(4)

routing_df

,message,predicted_intent,confidence,decision,predicted_team,routing_destination
0,i wnt to cancle my order,cancel_order,0.1613,HUMAN_REVIEW,Order Support,Human Review Queue
1,where is my oorder,track_order,0.1076,HUMAN_REVIEW,Order Support,Human Review Queue
2,i forgot my pasword,recover_password,0.6047,HUMAN_REVIEW,Account Support,Human Review Queue
3,hey where's my package?,delivery_period,0.2686,HUMAN_REVIEW,Delivery Support,Human Review Queue
4,need my money back asap,get_refund,0.7505,AUTO_ROUTE,Refund Support,Refund Support
5,how do i get my order cancelled,get_invoice,0.3309,HUMAN_REVIEW,Billing Support,Human Review Queue
6,refund?,get_refund,0.4442,HUMAN_REVIEW,Refund Support,Human Review Queue
7,password help,recover_password,0.5678,HUMAN_REVIEW,Account Support,Human Review Queue
8,track order,track_order,0.7874,AUTO_ROUTE,Order Support,Order Support
9,my parcel hasn't arrived yet,delivery_period,0.3828,HUMAN_REVIEW,Delivery Support,Human Review Queue


In [79]:
def predict_priority(message):
    message_lower = message.lower()

    high_priority_keywords = [
        "urgent",
        "urgently",
        "asap",
        "immediately",
        "charged twice",
        "charged multiple times",
        "money deducted",
        "payment deducted",
        "account locked",
        "can't access",
        "cannot access",
        "fraud",
        "unauthorized",
        "stolen",
        "security issue"
    ]

    medium_priority_keywords = [
        "refund",
        "cancel",
        "complaint",
        "payment issue",
        "not received",
        "delayed",
        "problem",
        "error",
        "failed"
    ]

    for keyword in high_priority_keywords:
        if keyword in message_lower:
            return "HIGH"

    for keyword in medium_priority_keywords:
        if keyword in message_lower:
            return "MEDIUM"

    return "LOW"

In [80]:
priority_test_tickets = [
    "URGENT! My payment was deducted but my order failed",
    "I want to cancel my order",
    "How can I change my account details?",
    "My account is locked and I can't access it",
    "I haven't received my refund yet",
    "What payment methods do you accept?",
    "I was charged twice for the same order"
]

for ticket in priority_test_tickets:
    priority = predict_priority(ticket)
    print(f"{ticket} -> {priority}")

URGENT! My payment was deducted but my order failed -> HIGH
I want to cancel my order -> MEDIUM
How can I change my account details? -> LOW
My account is locked and I can't access it -> HIGH
I haven't received my refund yet -> MEDIUM
What payment methods do you accept? -> LOW
I was charged twice for the same order -> HIGH


In [81]:
def route_ticket(message):
    predicted_intent, probability, decision = (
        predict_intent_with_confidence_combined(message)
    )

    predicted_team = intent_to_team[predicted_intent]

    if decision == "AUTO_ROUTE":
        routing_destination = predicted_team
    else:
        routing_destination = "Human Review Queue"

    priority = predict_priority(message)

    return {
        "message": message,
        "predicted_intent": predicted_intent,
        "confidence": probability,
        "decision": decision,
        "predicted_team": predicted_team,
        "routing_destination": routing_destination,
        "priority": priority
    }

In [82]:
results = []

for ticket in test_tickets:
    result = route_ticket(ticket)
    results.append(result)

routing_df = pd.DataFrame(results)

routing_df["confidence"] = routing_df["confidence"].round(4)

routing_df

,message,predicted_intent,confidence,decision,predicted_team,routing_destination,priority
0,i wnt to cancle my order,cancel_order,0.1613,HUMAN_REVIEW,Order Support,Human Review Queue,LOW
1,where is my oorder,track_order,0.1076,HUMAN_REVIEW,Order Support,Human Review Queue,LOW
2,i forgot my pasword,recover_password,0.6047,HUMAN_REVIEW,Account Support,Human Review Queue,LOW
3,hey where's my package?,delivery_period,0.2686,HUMAN_REVIEW,Delivery Support,Human Review Queue,LOW
4,need my money back asap,get_refund,0.7505,AUTO_ROUTE,Refund Support,Refund Support,HIGH
5,how do i get my order cancelled,get_invoice,0.3309,HUMAN_REVIEW,Billing Support,Human Review Queue,MEDIUM
6,refund?,get_refund,0.4442,HUMAN_REVIEW,Refund Support,Human Review Queue,MEDIUM
7,password help,recover_password,0.5678,HUMAN_REVIEW,Account Support,Human Review Queue,LOW
8,track order,track_order,0.7874,AUTO_ROUTE,Order Support,Order Support,LOW
9,my parcel hasn't arrived yet,delivery_period,0.3828,HUMAN_REVIEW,Delivery Support,Human Review Queue,LOW


# NEXT: Build the Final Ticket Processor

In [83]:
import uuid

def process_ticket(message):
    
    # 1. Predict intent + confidence
    predicted_intent, confidence, decision = (
        predict_intent_with_confidence_combined(message)
    )
    
    # 2. Find support team
    predicted_team = intent_to_team[predicted_intent]
    
    # 3. Predict priority
    priority = predict_priority(message)
    
    # 4. Decide final routing destination
    if decision == "AUTO_ROUTE":
        routing_destination = predicted_team
    else:
        routing_destination = "Human Review Queue"
    
    # 5. Generate ticket ID
    ticket_id = "TKT-" + str(uuid.uuid4())[:8].upper()
    
    return {
        "ticket_id": ticket_id,
        "message": message,
        "predicted_intent": predicted_intent,
        "confidence": round(confidence, 4),
        "priority": priority,
        "decision": decision,
        "predicted_team": predicted_team,
        "routing_destination": routing_destination
    }

In [84]:
ticket = process_ticket("I need my money back asap")

ticket

{'ticket_id': 'TKT-447B9A98',
 'message': 'I need my money back asap',
 'predicted_intent': 'get_refund',
 'confidence': np.float64(0.7464),
 'priority': 'HIGH',
 'decision': 'AUTO_ROUTE',
 'predicted_team': 'Refund Support',
 'routing_destination': 'Refund Support'}

In [85]:
for key, value in ticket.items():
    print(f"{key.replace('_', ' ').title():20}: {value}")

Ticket Id           : TKT-447B9A98
Message             : I need my money back asap
Predicted Intent    : get_refund
Confidence          : 0.7464
Priority            : HIGH
Decision            : AUTO_ROUTE
Predicted Team      : Refund Support
Routing Destination : Refund Support


In [86]:
test_tickets_extended = [
    "I want to cancel my order",
    "Where is my package?",
    "I forgot my password",
    "My payment was deducted but the order failed",
    "Can I get a refund?",
    "What payment methods do you accept?",
    "I want to change my delivery address",
    "I was charged twice for the same order",
    "How do I create a new account?",
    "I want to download my invoice"
]

In [87]:
results = []

for message in test_tickets_extended:
    result = process_ticket(message)
    results.append(result)

final_ticket_df = pd.DataFrame(results)

final_ticket_df

,ticket_id,message,predicted_intent,confidence,priority,decision,predicted_team,routing_destination
0,TKT-9067406B,I want to cancel my order,cancel_order,0.7466,MEDIUM,AUTO_ROUTE,Order Support,Order Support
1,TKT-F5BA5B33,Where is my package?,delivery_period,0.2606,LOW,HUMAN_REVIEW,Delivery Support,Human Review Queue
2,TKT-C6021D3E,I forgot my password,recover_password,0.8439,LOW,AUTO_ROUTE,Account Support,Account Support
3,TKT-98BF308C,My payment was deducted but the order failed,payment_issue,0.2593,MEDIUM,HUMAN_REVIEW,Payment Support,Human Review Queue
4,TKT-468BC746,Can I get a refund?,get_refund,0.8579,MEDIUM,AUTO_ROUTE,Refund Support,Refund Support
5,TKT-1B49AB2D,What payment methods do you accept?,check_payment_methods,0.9797,LOW,AUTO_ROUTE,Payment Support,Payment Support
6,TKT-3B3F86B8,I want to change my delivery address,change_shipping_address,0.9767,LOW,AUTO_ROUTE,Delivery Support,Delivery Support
7,TKT-CEF54391,I was charged twice for the same order,check_cancellation_fee,0.1246,HIGH,HUMAN_REVIEW,Order Support,Human Review Queue
8,TKT-D5EBEC75,How do I create a new account?,create_account,0.9704,LOW,AUTO_ROUTE,Account Support,Account Support
9,TKT-D5B7F3FD,I want to download my invoice,get_invoice,0.9927,LOW,AUTO_ROUTE,Billing Support,Billing Support


# Interface building

In [88]:
!pip install gradio


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [89]:
# Step 2 — Create the interface function
def analyze_ticket(message):
    
    if not message.strip():
        return (
            "Please enter a customer support message.",
            "",
            "",
            "",
            "",
            ""
        )

    result = process_ticket(message)

    ticket_id = result["ticket_id"]
    intent = result["predicted_intent"]
    confidence = f'{result["confidence"]:.2%}'
    priority = result["priority"]
    decision = result["decision"]
    team = result["predicted_team"]
    destination = result["routing_destination"]

    return (
        ticket_id,
        intent,
        confidence,
        priority,
        decision,
        f"{team} → {destination}"
    )

In [90]:
import gradio as gr

interface = gr.Interface(
    fn=analyze_ticket,
    
    inputs=gr.Textbox(
        lines=5,
        placeholder="Example: I was charged twice for my order",
        label="Customer Support Ticket"
    ),
    
    outputs=[
        gr.Textbox(label="Ticket ID"),
        gr.Textbox(label="Predicted Intent"),
        gr.Textbox(label="Confidence"),
        gr.Textbox(label="Priority"),
        gr.Textbox(label="Decision"),
        gr.Textbox(label="Routing")
    ],
    
    title="🤖 AI Customer Support Ticket Classifier V1",
    
    description=(
        "Enter a customer support message. "
        "The system will classify the intent, estimate confidence, "
        "assign priority, and determine the routing destination."
    ),
    
    submit_btn="Analyze Ticket",
    clear_btn="Clear"
)

interface.launch()

C:\Users\Si11191Sr\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.


# Version - 2

In [91]:
import gradio as gr


def analyze_ticket_ui(message):
    
    if not message.strip():
        return """
        <div class="empty-box">
            ⚠️ Please enter a customer support message.
        </div>
        """

    result = process_ticket(message)

    ticket_id = result["ticket_id"]
    intent = result["predicted_intent"]
    confidence = result["confidence"]
    priority = result["priority"]
    decision = result["decision"]
    team = result["predicted_team"]
    destination = result["routing_destination"]

    confidence_percent = confidence * 100

    # Priority styling
    if priority == "HIGH":
        priority_icon = "🔴"
        priority_class = "high"
    elif priority == "MEDIUM":
        priority_icon = "🟡"
        priority_class = "medium"
    else:
        priority_icon = "🟢"
        priority_class = "low"

    # Decision styling
    if decision == "AUTO_ROUTE":
        decision_icon = "🟢"
        decision_text = "Automatically Routed"
        decision_class = "auto"
    else:
        decision_icon = "🟠"
        decision_text = "Human Review Required"
        decision_class = "review"

    # Confidence bar
    confidence_color = (
        "#22c55e" if confidence >= 0.70
        else "#f59e0b" if confidence >= 0.50
        else "#ef4444"
    )

    return f"""
    <div class="ticket-card">

        <div class="ticket-header">
            <div>
                <div class="small-label">AI SUPPORT TICKET</div>
                <h2>Ticket Analysis</h2>
            </div>
            <div class="ticket-id">{ticket_id}</div>
        </div>

        <div class="section-title">🧠 Intent Classification</div>

        <div class="intent-box">
            {intent}
        </div>

        <div class="section-title">📊 Model Confidence</div>

        <div class="confidence-container">
            <div class="confidence-bar">
                <div class="confidence-fill"
                     style="width:{confidence_percent}%;
                            background:{confidence_color};">
                </div>
            </div>

            <div class="confidence-text">
                {confidence_percent:.2f}%
            </div>
        </div>

        <div class="result-grid">

            <div class="result-item">
                <div class="result-label">Priority</div>
                <div class="result-value {priority_class}">
                    {priority_icon} {priority}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Decision</div>
                <div class="result-value {decision_class}">
                    {decision_icon} {decision_text}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Support Team</div>
                <div class="result-value">
                    👥 {team}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Routing Destination</div>
                <div class="result-value">
                    📍 {destination}
                </div>
            </div>

        </div>

    </div>
    """


css = """
.ticket-card {
    padding: 28px;
    border-radius: 18px;
    background: #18181b;
    border: 1px solid #3f3f46;
    margin-top: 10px;
}

.ticket-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 28px;
}

.ticket-header h2 {
    margin: 5px 0 0 0;
    font-size: 26px;
}

.small-label {
    font-size: 12px;
    letter-spacing: 2px;
    color: #a1a1aa;
    font-weight: bold;
}

.ticket-id {
    padding: 9px 14px;
    border-radius: 8px;
    background: #27272a;
    font-family: monospace;
    font-size: 14px;
}

.section-title {
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 10px;
}

.intent-box {
    padding: 15px;
    border-radius: 10px;
    background: #27272a;
    font-family: monospace;
    font-size: 16px;
}

.confidence-container {
    display: flex;
    align-items: center;
    gap: 15px;
}

.confidence-bar {
    height: 14px;
    flex: 1;
    background: #3f3f46;
    border-radius: 10px;
    overflow: hidden;
}

.confidence-fill {
    height: 100%;
    border-radius: 10px;
}

.confidence-text {
    width: 70px;
    font-weight: bold;
}

.result-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 15px;
    margin-top: 25px;
}

.result-item {
    padding: 17px;
    border-radius: 12px;
    background: #27272a;
}

.result-label {
    font-size: 12px;
    color: #a1a1aa;
    margin-bottom: 8px;
}

.result-value {
    font-weight: bold;
    font-size: 15px;
}

.high {
    color: #ef4444;
}

.medium {
    color: #f59e0b;
}

.low {
    color: #22c55e;
}

.auto {
    color: #22c55e;
}

.review {
    color: #f59e0b;
}

.empty-box {
    padding: 30px;
    text-align: center;
    border-radius: 15px;
    background: #18181b;
    border: 1px solid #3f3f46;
}
"""


with gr.Blocks(css=css, title="AI Customer Support Classifier") as demo:

    gr.Markdown(
        """
        # 🤖 AI Customer Support Ticket Classifier V2

        ### Intelligent ticket classification, priority detection and routing
        """
    )

    with gr.Row():

        with gr.Column(scale=1):

            ticket_input = gr.Textbox(
                label="Customer Support Ticket",
                placeholder="Example: I was charged twice for my order",
                lines=7
            )

            analyze_button = gr.Button(
                "🔍 Analyze Ticket",
                variant="primary"
            )

            clear_button = gr.ClearButton(
                components=[ticket_input],
                value="🗑️ Clear"
            )

        with gr.Column(scale=1):

            result_output = gr.HTML(
                value="""
                <div class="empty-box">
                    🎫 Enter a customer ticket and click
                    <b>Analyze Ticket</b>
                </div>
                """
            )

    analyze_button.click(
        fn=analyze_ticket_ui,
        inputs=ticket_input,
        outputs=result_output
    )


demo.launch()

C:\Users\Si11191Sr\AppData\Local\Temp\ipykernel_57524\2863682754.py:249: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: css. Please pass these parameters to launch() instead.
  with gr.Blocks(css=css, title="AI Customer Support Classifier") as demo:


* Running on local URL:  http://127.0.0.1:7861
* To create a public link, set `share=True` in `launch()`.


# V3 = Ticket History + Live Dashboard Stats.

In [92]:
import gradio as gr
import pandas as pd


# ============================================================
# 1. ANALYZE TICKET
# ============================================================

def analyze_ticket_v3(message, history):

    if not message.strip():
        empty_result = """
        <div class="empty-box">
            ⚠️ Please enter a customer support message.
        </div>
        """

        return empty_result, history, history


    # Process ticket using our existing ML pipeline
    result = process_ticket(message)

    ticket_id = result["ticket_id"]
    intent = result["predicted_intent"]
    confidence = result["confidence"]
    priority = result["priority"]
    decision = result["decision"]
    team = result["predicted_team"]
    destination = result["routing_destination"]


    # ========================================================
    # VISUAL SETTINGS
    # ========================================================

    confidence_percent = confidence * 100


    # Priority
    if priority == "HIGH":
        priority_icon = "🔴"
        priority_class = "high"

    elif priority == "MEDIUM":
        priority_icon = "🟡"
        priority_class = "medium"

    else:
        priority_icon = "🟢"
        priority_class = "low"


    # Decision
    if decision == "AUTO_ROUTE":
        decision_icon = "🟢"
        decision_text = "Automatically Routed"
        decision_class = "auto"

    else:
        decision_icon = "🟠"
        decision_text = "Human Review Required"
        decision_class = "review"


    # Confidence color
    if confidence >= 0.70:
        confidence_color = "#22c55e"

    elif confidence >= 0.50:
        confidence_color = "#f59e0b"

    else:
        confidence_color = "#ef4444"


    # ========================================================
    # RESULT CARD
    # ========================================================

    result_html = f"""
    <div class="ticket-card">

        <div class="ticket-header">

            <div>
                <div class="small-label">
                    AI SUPPORT TICKET
                </div>

                <h2>Ticket Analysis</h2>
            </div>

            <div class="ticket-id">
                {ticket_id}
            </div>

        </div>


        <div class="section-title">
            🧠 Intent Classification
        </div>

        <div class="intent-box">
            {intent}
        </div>


        <div class="section-title">
            📊 Model Confidence
        </div>

        <div class="confidence-container">

            <div class="confidence-bar">

                <div
                    class="confidence-fill"
                    style="
                        width:{confidence_percent}%;
                        background:{confidence_color};
                    "
                >
                </div>

            </div>

            <div class="confidence-text">
                {confidence_percent:.2f}%
            </div>

        </div>


        <div class="result-grid">

            <div class="result-item">

                <div class="result-label">
                    Priority
                </div>

                <div class="result-value {priority_class}">
                    {priority_icon} {priority}
                </div>

            </div>


            <div class="result-item">

                <div class="result-label">
                    Decision
                </div>

                <div class="result-value {decision_class}">
                    {decision_icon} {decision_text}
                </div>

            </div>


            <div class="result-item">

                <div class="result-label">
                    Support Team
                </div>

                <div class="result-value">
                    👥 {team}
                </div>

            </div>


            <div class="result-item">

                <div class="result-label">
                    Routing Destination
                </div>

                <div class="result-value">
                    📍 {destination}
                </div>

            </div>

        </div>

    </div>
    """


    # ========================================================
    # ADD TICKET TO HISTORY
    # ========================================================

    new_ticket = {
        "Ticket ID": ticket_id,
        "Message": message,
        "Intent": intent,
        "Confidence": round(confidence * 100, 2),
        "Priority": priority,
        "Decision": decision,
        "Team": team,
        "Destination": destination
    }


    history = history + [new_ticket]


    history_df = pd.DataFrame(history)


    # ========================================================
    # RETURN
    # ========================================================

    return result_html, history, history_df


# ============================================================
# 2. DASHBOARD STATISTICS
# ============================================================

def update_stats(history):

    if not history:
        total = auto_routed = human_review = 0
        high_priority = medium_priority = low_priority = 0

    else:
        df = pd.DataFrame(history)

        total = len(df)

        auto_routed = (df["Decision"] == "AUTO_ROUTE").sum()
        human_review = (df["Decision"] == "HUMAN_REVIEW").sum()

        high_priority = (df["Priority"] == "HIGH").sum()
        medium_priority = (df["Priority"] == "MEDIUM").sum()
        low_priority = (df["Priority"] == "LOW").sum()


    return (

        f"""
        <div class="stat-box">
            <div class="stat-number">{total}</div>
            <div class="stat-label">TOTAL TICKETS</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{auto_routed}</div>
            <div class="stat-label">AUTO ROUTED</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{human_review}</div>
            <div class="stat-label">HUMAN REVIEW</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{high_priority}</div>
            <div class="stat-label">🔴 HIGH PRIORITY</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{medium_priority}</div>
            <div class="stat-label">🟡 MEDIUM PRIORITY</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{low_priority}</div>
            <div class="stat-label">🟢 LOW PRIORITY</div>
        </div>
        """
    )


# ============================================================
# 3. CLEAR HISTORY
# ============================================================

def clear_history():

    return (
        [],
        pd.DataFrame(
            columns=[
                "Ticket ID",
                "Message",
                "Intent",
                "Confidence",
                "Priority",
                "Decision",
                "Team",
                "Destination"
            ]
        ),
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
    )


# ============================================================
# 4. CSS
# ============================================================

css = """

.ticket-card {

    padding: 28px;

    border-radius: 18px;

    background: #18181b;

    border: 1px solid #3f3f46;

    margin-top: 10px;
}


.ticket-header {

    display: flex;

    justify-content: space-between;

    align-items: center;

    margin-bottom: 28px;
}


.ticket-header h2 {

    margin: 5px 0 0 0;

    font-size: 26px;
}


.small-label {

    font-size: 12px;

    letter-spacing: 2px;

    color: #a1a1aa;

    font-weight: bold;
}


.ticket-id {

    padding: 9px 14px;

    border-radius: 8px;

    background: #27272a;

    font-family: monospace;

    font-size: 14px;
}


.section-title {

    font-weight: bold;

    margin-top: 20px;

    margin-bottom: 10px;
}


.intent-box {

    padding: 15px;

    border-radius: 10px;

    background: #27272a;

    font-family: monospace;

    font-size: 16px;
}


.confidence-container {

    display: flex;

    align-items: center;

    gap: 15px;
}


.confidence-bar {

    height: 14px;

    flex: 1;

    background: #3f3f46;

    border-radius: 10px;

    overflow: hidden;
}


.confidence-fill {

    height: 100%;

    border-radius: 10px;
}


.confidence-text {

    width: 70px;

    font-weight: bold;
}


.result-grid {

    display: grid;

    grid-template-columns: 1fr 1fr;

    gap: 15px;

    margin-top: 25px;
}


.result-item {

    padding: 17px;

    border-radius: 12px;

    background: #27272a;
}


.result-label {

    font-size: 12px;

    color: #a1a1aa;

    margin-bottom: 8px;
}


.result-value {

    font-weight: bold;

    font-size: 15px;
}


.high {

    color: #ef4444;
}


.medium {

    color: #f59e0b;
}


.low {

    color: #22c55e;
}


.auto {

    color: #22c55e;
}


.review {

    color: #f59e0b;
}


.empty-box {

    padding: 30px;

    text-align: center;

    border-radius: 15px;

    background: #18181b;

    border: 1px solid #3f3f46;
}


.stat-box {

    padding: 18px;

    border-radius: 14px;

    background: #18181b;

    border: 1px solid #3f3f46;

    text-align: center;
}


.stat-number {

    font-size: 28px;

    font-weight: bold;

    margin-bottom: 5px;
}


.stat-label {

    font-size: 12px;

    color: #a1a1aa;
}


"""



# ============================================================
# 5. BUILD GRADIO APP
# ============================================================

with gr.Blocks(
    css=css,
    title="AI Customer Support Classifier"
) as demo:


    # Session history
    history_state = gr.State([])


    # --------------------------------------------------------
    # HEADER
    # --------------------------------------------------------

    gr.Markdown(
        """
        # 🤖 AI Customer Support Ticket Classifier V3

        ### Intelligent ticket classification, priority detection and routing
        """
    )


    # --------------------------------------------------------
    # TICKET ANALYZER
    # --------------------------------------------------------

    with gr.Row():


        # LEFT SIDE
        with gr.Column(scale=1):


            ticket_input = gr.Textbox(

                label="Customer Support Ticket",

                placeholder=(
                    "Example: I was charged twice for my order"
                ),

                lines=7
            )


            analyze_button = gr.Button(

                "🔍 Analyze Ticket",

                variant="primary"
            )


            clear_input_button = gr.ClearButton(

                components=[ticket_input],

                value="🗑️ Clear"
            )


        # RIGHT SIDE
        with gr.Column(scale=1):


            result_output = gr.HTML(

                value="""
                <div class="empty-box">

                    🎫 Enter a customer ticket and click
                    <b>Analyze Ticket</b>

                </div>
                """
            )


    # --------------------------------------------------------
    # DASHBOARD
    # --------------------------------------------------------

    gr.Markdown(
        """
        ## 📊 Ticket Dashboard
        """
    )


    with gr.Row():


        total_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">TOTAL TICKETS</div>
            </div>
            """
        )


        auto_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">AUTO ROUTED</div>
            </div>
            """
        )


        review_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">HUMAN REVIEW</div>
            </div>
            """
        )


    with gr.Row():


        high_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">🔴 HIGH PRIORITY</div>
            </div>
            """
        )


        medium_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">🟡 MEDIUM PRIORITY</div>
            </div>
            """
        )


        low_stat = gr.HTML(
            """
            <div class="stat-box">
                <div class="stat-number">0</div>
                <div class="stat-label">🟢 LOW PRIORITY</div>
            </div>
            """
        )


    # --------------------------------------------------------
    # TICKET HISTORY
    # --------------------------------------------------------

    gr.Markdown(
        """
        ## 📋 Processed Ticket History
        """
    )


    history_table = gr.Dataframe(

        headers=[
            "Ticket ID",
            "Message",
            "Intent",
            "Confidence",
            "Priority",
            "Decision",
            "Team",
            "Destination"
        ],

        datatype=[
            "str",
            "str",
            "str",
            "number",
            "str",
            "str",
            "str",
            "str"
        ],

        value=pd.DataFrame(
            columns=[
                "Ticket ID",
                "Message",
                "Intent",
                "Confidence",
                "Priority",
                "Decision",
                "Team",
                "Destination"
            ]
        ),

        interactive=False
    )


    # --------------------------------------------------------
    # CLEAR HISTORY
    # --------------------------------------------------------

    clear_history_button = gr.Button(
        "🗑️ Clear Ticket History"
    )


    # ========================================================
    # EVENTS
    # ========================================================

    analyze_button.click(

        fn=analyze_ticket_v3,

        inputs=[
            ticket_input,
            history_state
        ],

        outputs=[
            result_output,
            history_state,
            history_table
        ]

    ).then(

        fn=update_stats,

        inputs=history_state,

        outputs=[
            total_stat,
            auto_stat,
            review_stat,
            high_stat,
            medium_stat,
            low_stat
        ]

    )


    clear_history_button.click(

        fn=clear_history,

        inputs=[],

        outputs=[
            history_state,
            history_table,
            total_stat,
            auto_stat,
            review_stat,
            high_stat,
            medium_stat,
            low_stat
        ]

    )


# ============================================================
# 6. LAUNCH
# ============================================================

demo.launch()

C:\Users\Si11191Sr\AppData\Local\Temp\ipykernel_57524\1352784966.py:576: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: css. Please pass these parameters to launch() instead.
  with gr.Blocks(


* Running on local URL:  http://127.0.0.1:7862
* To create a public link, set `share=True` in `launch()`.


In [93]:
import gradio as gr
import pandas as pd


# ============================================================
# 1. ANALYZE TICKET
# ============================================================

def analyze_ticket_v4(message, history):

    if not message.strip():
        return """
        <div class="empty-box">
            ⚠️ Please enter a customer support message.
        </div>
        """, history, pd.DataFrame(history), *update_stats(history)

    result = process_ticket(message)

    ticket_id = result["ticket_id"]
    intent = result["predicted_intent"]
    confidence = result["confidence"]
    priority = result["priority"]
    decision = result["decision"]
    team = result["predicted_team"]
    destination = result["routing_destination"]

    confidence_percent = confidence * 100

    # Priority styling
    if priority == "HIGH":
        priority_icon = "🔴"
        priority_class = "high"
    elif priority == "MEDIUM":
        priority_icon = "🟡"
        priority_class = "medium"
    else:
        priority_icon = "🟢"
        priority_class = "low"

    # Decision styling
    if decision == "AUTO_ROUTE":
        decision_icon = "🟢"
        decision_text = "Automatically Routed"
        decision_class = "auto"
    else:
        decision_icon = "🟠"
        decision_text = "Human Review Required"
        decision_class = "review"

    # Confidence color
    if confidence >= 0.70:
        confidence_color = "#22c55e"
    elif confidence >= 0.50:
        confidence_color = "#f59e0b"
    else:
        confidence_color = "#ef4444"

    # Result card
    result_html = f"""
    <div class="ticket-card">

        <div class="ticket-header">

            <div>
                <div class="small-label">
                    AI SUPPORT TICKET
                </div>

                <h2>Ticket Analysis</h2>
            </div>

            <div class="ticket-id">
                {ticket_id}
            </div>

        </div>

        <div class="section-title">
            🧠 Intent Classification
        </div>

        <div class="intent-box">
            {intent}
        </div>

        <div class="section-title">
            📊 Model Confidence
        </div>

        <div class="confidence-container">

            <div class="confidence-bar">

                <div
                    class="confidence-fill"
                    style="
                        width:{confidence_percent}%;
                        background:{confidence_color};
                    "
                ></div>

            </div>

            <div class="confidence-text">
                {confidence_percent:.2f}%
            </div>

        </div>

        <div class="result-grid">

            <div class="result-item">
                <div class="result-label">Priority</div>
                <div class="result-value {priority_class}">
                    {priority_icon} {priority}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Decision</div>
                <div class="result-value {decision_class}">
                    {decision_icon} {decision_text}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Support Team</div>
                <div class="result-value">
                    👥 {team}
                </div>
            </div>

            <div class="result-item">
                <div class="result-label">Routing Destination</div>
                <div class="result-value">
                    📍 {destination}
                </div>
            </div>

        </div>

    </div>
    """

    new_ticket = {
        "Ticket ID": ticket_id,
        "Message": message,
        "Intent": intent,
        "Confidence": round(confidence * 100, 2),
        "Priority": priority,
        "Decision": decision,
        "Team": team,
        "Destination": destination
    }

    history = history + [new_ticket]

    history_df = pd.DataFrame(history)

    return (
        result_html,
        history,
        history_df,
        *update_stats(history)
    )


# ============================================================
# 2. DASHBOARD STATISTICS
# ============================================================

def update_stats(history):

    if not history:
        total = 0
        auto_routed = 0
        human_review = 0
        high_priority = 0
        medium_priority = 0
        low_priority = 0

    else:
        df = pd.DataFrame(history)

        total = len(df)

        auto_routed = (df["Decision"] == "AUTO_ROUTE").sum()
        human_review = (df["Decision"] == "HUMAN_REVIEW").sum()

        high_priority = (df["Priority"] == "HIGH").sum()
        medium_priority = (df["Priority"] == "MEDIUM").sum()
        low_priority = (df["Priority"] == "LOW").sum()

    return (
        f"""
        <div class="stat-box">
            <div class="stat-number">{total}</div>
            <div class="stat-label">TOTAL TICKETS</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{auto_routed}</div>
            <div class="stat-label">AUTO ROUTED</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{human_review}</div>
            <div class="stat-label">HUMAN REVIEW</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{high_priority}</div>
            <div class="stat-label">🔴 HIGH PRIORITY</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{medium_priority}</div>
            <div class="stat-label">🟡 MEDIUM PRIORITY</div>
        </div>
        """,

        f"""
        <div class="stat-box">
            <div class="stat-number">{low_priority}</div>
            <div class="stat-label">🟢 LOW PRIORITY</div>
        </div>
        """
    )


# ============================================================
# 3. FILTER TICKETS
# ============================================================

def filter_tickets(history, search, priority, decision, team):

    if not history:
        return pd.DataFrame(
            columns=[
                "Ticket ID",
                "Message",
                "Intent",
                "Confidence",
                "Priority",
                "Decision",
                "Team",
                "Destination"
            ]
        )

    df = pd.DataFrame(history)

    # Search
    if search.strip():
        search_text = search.lower()

        mask = (
            df["Ticket ID"].str.lower().str.contains(search_text, na=False)
            |
            df["Message"].str.lower().str.contains(search_text, na=False)
            |
            df["Intent"].str.lower().str.contains(search_text, na=False)
        )

        df = df[mask]

    # Priority
    if priority != "ALL":
        df = df[df["Priority"] == priority]

    # Decision
    if decision != "ALL":
        df = df[df["Decision"] == decision]

    # Team
    if team != "ALL":
        df = df[df["Team"] == team]

    return df.reset_index(drop=True)


# ============================================================
# 4. RESET FILTERS
# ============================================================

def reset_filters(history):

    df = pd.DataFrame(history)

    if df.empty:
        df = pd.DataFrame(
            columns=[
                "Ticket ID",
                "Message",
                "Intent",
                "Confidence",
                "Priority",
                "Decision",
                "Team",
                "Destination"
            ]
        )

    return "", "ALL", "ALL", "ALL", df


# ============================================================
# 5. CLEAR EVERYTHING
# ============================================================

def clear_all():

    empty_df = pd.DataFrame(
        columns=[
            "Ticket ID",
            "Message",
            "Intent",
            "Confidence",
            "Priority",
            "Decision",
            "Team",
            "Destination"
        ]
    )

    stats = update_stats([])

    return (
        [],
        empty_df,
        *stats,
        """
        <div class="empty-box">
            🎫 Enter a customer ticket and click
            <b>Analyze Ticket</b>
        </div>
        """
    )


# ============================================================
# 6. CSS
# ============================================================

css = """

.ticket-card {
    padding: 28px;
    border-radius: 18px;
    background: #18181b;
    border: 1px solid #3f3f46;
}

.ticket-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 28px;
}

.ticket-header h2 {
    margin: 5px 0 0 0;
    font-size: 26px;
}

.small-label {
    font-size: 12px;
    letter-spacing: 2px;
    color: #a1a1aa;
    font-weight: bold;
}

.ticket-id {
    padding: 9px 14px;
    border-radius: 8px;
    background: #27272a;
    font-family: monospace;
}

.section-title {
    font-weight: bold;
    margin-top: 20px;
    margin-bottom: 10px;
}

.intent-box {
    padding: 15px;
    border-radius: 10px;
    background: #27272a;
    font-family: monospace;
}

.confidence-container {
    display: flex;
    align-items: center;
    gap: 15px;
}

.confidence-bar {
    height: 14px;
    flex: 1;
    background: #3f3f46;
    border-radius: 10px;
    overflow: hidden;
}

.confidence-fill {
    height: 100%;
    border-radius: 10px;
}

.confidence-text {
    width: 70px;
    font-weight: bold;
}

.result-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 15px;
    margin-top: 25px;
}

.result-item {
    padding: 17px;
    border-radius: 12px;
    background: #27272a;
}

.result-label {
    font-size: 12px;
    color: #a1a1aa;
    margin-bottom: 8px;
}

.result-value {
    font-weight: bold;
}

.high {
    color: #ef4444;
}

.medium {
    color: #f59e0b;
}

.low {
    color: #22c55e;
}

.auto {
    color: #22c55e;
}

.review {
    color: #f59e0b;
}

.empty-box {
    padding: 30px;
    text-align: center;
    border-radius: 15px;
    background: #18181b;
    border: 1px solid #3f3f46;
}

.stat-box {
    padding: 18px;
    border-radius: 14px;
    background: #18181b;
    border: 1px solid #3f3f46;
    text-align: center;
}

.stat-number {
    font-size: 28px;
    font-weight: bold;
}

.stat-label {
    font-size: 12px;
    color: #a1a1aa;
}

"""


# ============================================================
# 7. BUILD V4
# ============================================================

with gr.Blocks(
    css=css,
    title="AI Customer Support Classifier"
) as demo:

    history_state = gr.State([])

    gr.Markdown(
        """
        # 🤖 AI Customer Support Ticket Classifier V4

        ### Intelligent ticket classification, priority detection and routing
        """
    )


    # --------------------------------------------------------
    # ANALYZER
    # --------------------------------------------------------

    with gr.Row():

        with gr.Column(scale=1):

            ticket_input = gr.Textbox(
                label="Customer Support Ticket",
                placeholder="Example: I was charged twice for my order",
                lines=7
            )

            analyze_button = gr.Button(
                "🔍 Analyze Ticket",
                variant="primary"
            )

            clear_input = gr.ClearButton(
                [ticket_input],
                value="🗑️ Clear"
            )


        with gr.Column(scale=1):

            result_output = gr.HTML(
                """
                <div class="empty-box">
                    🎫 Enter a customer ticket and click
                    <b>Analyze Ticket</b>
                </div>
                """
            )


    # --------------------------------------------------------
    # DASHBOARD
    # --------------------------------------------------------

    gr.Markdown("## 📊 Ticket Dashboard")

    with gr.Row():

        total_stat = gr.HTML()

        auto_stat = gr.HTML()

        review_stat = gr.HTML()

    with gr.Row():

        high_stat = gr.HTML()

        medium_stat = gr.HTML()

        low_stat = gr.HTML()


    # --------------------------------------------------------
    # FILTERS
    # --------------------------------------------------------

    gr.Markdown("## 🔎 Ticket Queue")

    with gr.Row():

        search_box = gr.Textbox(
            label="Search",
            placeholder="Search message, intent or ticket ID..."
        )

        priority_filter = gr.Dropdown(
            choices=["ALL", "HIGH", "MEDIUM", "LOW"],
            value="ALL",
            label="Priority"
        )

        decision_filter = gr.Dropdown(
            choices=["ALL", "AUTO_ROUTE", "HUMAN_REVIEW"],
            value="ALL",
            label="Decision"
        )

        team_filter = gr.Dropdown(
            choices=[
                "ALL",
                "Order Support",
                "Delivery Support",
                "Payment Support",
                "Refund Support",
                "Billing Support",
                "Account Support",
                "Customer Service",
                "Subscription Support"
            ],
            value="ALL",
            label="Support Team"
        )


    with gr.Row():

        apply_filter_button = gr.Button(
            "🔎 Apply Filters",
            variant="primary"
        )

        reset_filter_button = gr.Button(
            "↩️ Reset Filters"
        )


    # --------------------------------------------------------
    # HISTORY TABLE
    # --------------------------------------------------------

    history_table = gr.Dataframe(
        headers=[
            "Ticket ID",
            "Message",
            "Intent",
            "Confidence",
            "Priority",
            "Decision",
            "Team",
            "Destination"
        ],
        datatype=[
            "str",
            "str",
            "str",
            "number",
            "str",
            "str",
            "str",
            "str"
        ],
        interactive=False
    )


    # --------------------------------------------------------
    # CLEAR ALL
    # --------------------------------------------------------

    clear_history_button = gr.Button(
        "🗑️ Clear All Tickets"
    )


    # ========================================================
    # EVENTS
    # ========================================================

    analyze_button.click(

        fn=analyze_ticket_v4,

        inputs=[
            ticket_input,
            history_state
        ],

        outputs=[
            result_output,
            history_state,
            history_table,
            total_stat,
            auto_stat,
            review_stat,
            high_stat,
            medium_stat,
            low_stat
        ]
    )


    apply_filter_button.click(

        fn=filter_tickets,

        inputs=[
            history_state,
            search_box,
            priority_filter,
            decision_filter,
            team_filter
        ],

        outputs=history_table
    )


    reset_filter_button.click(

        fn=reset_filters,

        inputs=[history_state],

        outputs=[
            search_box,
            priority_filter,
            decision_filter,
            team_filter,
            history_table
        ]
    )


    clear_history_button.click(

        fn=clear_all,

        inputs=[],

        outputs=[
            history_state,
            history_table,
            total_stat,
            auto_stat,
            review_stat,
            high_stat,
            medium_stat,
            low_stat,
            result_output
        ]
    )


demo.launch()

C:\Users\Si11191Sr\AppData\Local\Temp\ipykernel_57524\3164786530.py:502: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: css. Please pass these parameters to launch() instead.
  with gr.Blocks(


* Running on local URL:  http://127.0.0.1:7863
* To create a public link, set `share=True` in `launch()`.


In [94]:
# for testing

test_message = "I was charged twice for my order"

result = analyze_ticket_v4(test_message, [])

print(result)

('\n    <div class="ticket-card">\n\n        <div class="ticket-header">\n\n            <div>\n                <div class="small-label">\n                    AI SUPPORT TICKET\n                </div>\n\n                <h2>Ticket Analysis</h2>\n            </div>\n\n            <div class="ticket-id">\n                TKT-19C5DC7E\n            </div>\n\n        </div>\n\n        <div class="section-title">\n            🧠 Intent Classification\n        </div>\n\n        <div class="intent-box">\n            change_order\n        </div>\n\n        <div class="section-title">\n            📊 Model Confidence\n        </div>\n\n        <div class="confidence-container">\n\n            <div class="confidence-bar">\n\n                <div\n                    class="confidence-fill"\n                    style="\n                        width:9.51%;\n                        background:#ef4444;\n                    "\n                ></div>\n\n            </div>\n\n            <div class="conf

# Save our trained models

Currently your models exist only in Jupyter's memory:

- tfidf
- char_tfidf
- combined_model

If you close/restart Jupyter, they're gone from memory.

So we're going to save them as files.

In [95]:
import joblib
import os

os.makedirs("models", exist_ok=True)

joblib.dump(tfidf, "models/word_tfidf.joblib")
joblib.dump(char_tfidf, "models/char_tfidf.joblib")
joblib.dump(combined_model, "models/combined_model.joblib")

print("Models saved successfully!")

Models saved successfully!
